---
title: Scraping de Editoriales y Librerías
author: ''
date: '2019-11-18'
slug: scraping-de-editoriales-y-librerías
categories: []
tags: []
subtitle: 'Un trabajo de Social Data Analytics'
summary: 'Scraping de Twitter e Instagram'
authors: []
lastmod: '2019-11-18T12:38:48-03:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
**Este año fui parte de la primera camada del curso Social Data Analytics impartido por EANT. Como no podía ser de otra manera, mi trabajo final fue sobre el sector editorial local**

En la cursada intensiva repasamos los fundamentos de la programación orientada a objetos, el trabajo con bases de datos y la interacción con APIs. En el segundo módulo, "Data Science para las Ciencias Sociales", aplicamos técnicas de web scraping y text mining en Python a diversos corpus.

En mi trabajo final elegí llevar a cabo una limitada auditoría de uso de redes sociales de librerías y editoriales con actividad en argentina. Para scrapear Twitter utilicé la librería TwitterAPI y Pandas para manejar los datos: en el caso de Instagram, fue necesario utilizar InstagramAPI y modificar una serie de funciones para poder scrapear feeds enteros y los comentarios recibidos por una cuenta desde su creación. 

<iframe src="https://onedrive.live.com/embed?cid=B9BB54C1ABD9A1D0&resid=B9BB54C1ABD9A1D0%21117&authkey=APN0bBSfdRYge74&em=2" width="610" height="367" frameborder="0" scrolling="no"></iframe>